In [1]:
import pandas as pd
import numpy as np

In [2]:
# Crear el CSV de población por distrito a partir de los datos del Padrón Municipal
poblacion_distritos = pd.DataFrame({
    'distrito': ['Centro', 'Arganzuela', 'Retiro', 'Salamanca', 'Chamartín',
                 'Tetuán', 'Chamberí', 'Fuencarral-El Pardo', 'Moncloa-Aravaca',
                 'Latina', 'Carabanchel', 'Usera', 'Puente de Vallecas',
                 'Moratalaz', 'Ciudad Lineal', 'Hortaleza', 'Villaverde',
                 'Villa de Vallecas', 'Vicálvaro', 'San Blas-Canillejas', 'Barajas'],
    'poblacion_total': [141800, 158550, 118863, 147256, 148093, 167776, 141522,
                         256037, 126257, 251139, 278090, 152937, 257924, 94405,
                         230334, 209178, 172551, 127566, 97860, 168526, 50613]
})

poblacion_distritos.to_csv('../data/raw/poblacion_distritos.csv', index=False)
poblacion_distritos

               distrito  poblacion_total
0                Centro           141800
1            Arganzuela           158550
2                Retiro           118863
3             Salamanca           147256
4             Chamartín           148093
5                Tetuán           167776
6              Chamberí           141522
7   Fuencarral-El Pardo           256037
8       Moncloa-Aravaca           126257
9                Latina           251139
10          Carabanchel           278090
11                Usera           152937
12   Puente de Vallecas           257924
13            Moratalaz            94405
14        Ciudad Lineal           230334
15            Hortaleza           209178
16           Villaverde           172551
17    Villa de Vallecas           127566
18            Vicálvaro            97860
19  San Blas-Canillejas           168526
20              Barajas            50613

In [3]:
# Crear el CSV de renta media por hogar y distrito
renta_distritos = pd.DataFrame({
    'distrito': ['Chamartín', 'Moncloa-Aravaca', 'Salamanca', 'Chamberí', 'Retiro',
                 'Fuencarral-El Pardo', 'Hortaleza', 'Barajas', 'Arganzuela',
                 'Ciudad Lineal', 'Tetuán', 'Centro', 'San Blas-Canillejas',
                 'Vicálvaro', 'Moratalaz', 'Villa de Vallecas', 'Latina',
                 'Carabanchel', 'Villaverde', 'Usera', 'Puente de Vallecas'],
    'renta_media_hogar': [79274, 71711, 69147, 65174, 64787, 62385, 61472, 58405,
                           52857, 46937, 45762, 44958, 44468, 42870, 42823, 39836,
                           38078, 36350, 35011, 34651, 32666]
})

renta_distritos.to_csv('../data/raw/renta_distritos.csv', index=False)
renta_distritos

               distrito  renta_media_hogar
0             Chamartín              79274
1       Moncloa-Aravaca              71711
2             Salamanca              69147
3              Chamberí              65174
4                Retiro              64787
5   Fuencarral-El Pardo              62385
6             Hortaleza              61472
7               Barajas              58405
8            Arganzuela              52857
9         Ciudad Lineal              46937
10               Tetuán              45762
11               Centro              44958
12  San Blas-Canillejas              44468
13            Vicálvaro              42870
14            Moratalaz              42823
15    Villa de Vallecas              39836
16               Latina              38078
17          Carabanchel              36350
18           Villaverde              35011
19                Usera              34651
20   Puente de Vallecas              32666

In [4]:
# Crear el CSV de precio de alquiler de referencia por distrito
# Fuente: Ayuntamiento de Madrid — Sistema Estatal de Índices de Referencia del Precio del Alquiler (2022)
# Variable: cuantía media de arrendamiento, vivienda colectiva, mediana (€/mes)
alquiler_distritos = pd.DataFrame({
    'distrito': ['Centro', 'Arganzuela', 'Retiro', 'Salamanca', 'Chamartín',
                 'Tetuán', 'Chamberí', 'Fuencarral-El Pardo', 'Moncloa-Aravaca',
                 'Latina', 'Carabanchel', 'Usera', 'Puente de Vallecas',
                 'Moratalaz', 'Ciudad Lineal', 'Hortaleza', 'Villaverde',
                 'Villa de Vallecas', 'Vicálvaro', 'San Blas-Canillejas', 'Barajas'],
    'alquiler_medio_mes': [825.00, 850.00, 950.00, 969.21, 951.72, 756.23, 998.75,
                            894.61, 900.49, 651.95, 650.00, 645.09, 600.01, 703.40,
                            735.75, 896.61, 600.00, 695.00, 700.00, 735.00, 825.74]
})

alquiler_distritos.to_csv('../data/raw/alquiler_referencia_distritos.csv', index=False)
alquiler_distritos

               distrito  alquiler_medio_mes
0                Centro              825.00
1            Arganzuela              850.00
2                Retiro              950.00
3             Salamanca              969.21
4             Chamartín              951.72
5                Tetuán              756.23
6              Chamberí              998.75
7   Fuencarral-El Pardo              894.61
8       Moncloa-Aravaca              900.49
9                Latina              651.95
10          Carabanchel              650.00
11                Usera              645.09
12   Puente de Vallecas              600.01
13            Moratalaz              703.40
14        Ciudad Lineal              735.75
15            Hortaleza              896.61
16           Villaverde              600.00
17    Villa de Vallecas              695.00
18            Vicálvaro              700.00
19  San Blas-Canillejas              735.00
20              Barajas              825.74

In [5]:
# Crear el CSV de eventos/grandes recintos por distrito
eventos_distritos = pd.DataFrame({
    'distrito': ['Centro', 'Arganzuela', 'Retiro', 'Salamanca', 'Chamartín',
                 'Tetuán', 'Chamberí', 'Fuencarral-El Pardo', 'Moncloa-Aravaca',
                 'Latina', 'Carabanchel', 'Usera', 'Puente de Vallecas',
                 'Moratalaz', 'Ciudad Lineal', 'Hortaleza', 'Villaverde',
                 'Villa de Vallecas', 'Vicálvaro', 'San Blas-Canillejas', 'Barajas'],
    'tiene_gran_recinto': [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1]
})

eventos_distritos.to_csv('../data/raw/eventos_distritos.csv', index=False)
eventos_distritos

               distrito  tiene_gran_recinto
0                Centro                   1
1            Arganzuela                   0
2                Retiro                   0
3             Salamanca                   0
4             Chamartín                   1
5                Tetuán                   0
6              Chamberí                   0
7   Fuencarral-El Pardo                   0
8       Moncloa-Aravaca                   1
9                Latina                   0
10          Carabanchel                   0
11                Usera                   0
12   Puente de Vallecas                   0
13            Moratalaz                   0
14        Ciudad Lineal                   0
15            Hortaleza                   1
16           Villaverde                   0
17    Villa de Vallecas                   0
18            Vicálvaro                   0
19  San Blas-Canillejas                   1
20              Barajas                   1

In [6]:
# Cargar el dataset limpio de Airbnb
df = pd.read_csv('../data/processed/madrid_airbnb_clean.csv')

# Cargar las 5 fuentes de enriquecimiento
poblacion = pd.read_csv('../data/raw/poblacion_distritos.csv')
renta = pd.read_csv('../data/raw/renta_distritos.csv')
alquiler = pd.read_csv('../data/raw/alquiler_referencia_distritos.csv')
eventos = pd.read_csv('../data/raw/eventos_distritos.csv')
vut = pd.read_excel('../data/raw/VIVIENDAS_USO_TURISTICO.xlsx')

print(df.shape)
print(poblacion.shape, renta.shape, alquiler.shape, eventos.shape, vut.shape)

(19618, 16)
(21, 2) (21, 2) (21, 2) (21, 2) (997, 12)

In [7]:
# Revisar cómo vienen los nombres de distrito en cada fuente
print(df.columns.tolist())
print()
print(vut.columns.tolist())
print()
print(vut['DISTRITO'].unique())  # ajusta el nombre de columna si no es exactamente así

['id', 'name', 'host_id', 'host_name', 'neighbourhood_group', 'neighbourhood', 'latitude', 'longitude', 'room_type', 'price', 'minimum_nights', 'number_of_reviews', 'last_review', 'reviews_per_month', 'calculated_host_listings_count', 'availability_365']

['COD_NDP', 'DECRETO_LU', 'DISTRITO', 'DIRECCION', 'PLANTA', 'UNIDADES_VUT', 'EXPEDIENTE_LU', 'TIPO', 'RESOLUCION_LU', 'EXPEDIENTE_LF', 'RESOLUCION_LF', 'DECRETO  LF']

<StringArray>
[                                      'Distrito de Arganzuela',
                                         'Distrito de Chamberí',
                                           'Distrito de Centro',
                                           'Distrito de Tetuan',
                                        'Distrito de Salamanca',
                                           'Distrito de Retiro',
                                        'Distrito de Hortaleza',
                                    'Distrito de Ciudad Lineal',
                                      'Distrito de Carabanchel',
                                            'Distrito de Usera',
                                           'Distrito de Latina',
                                        'Distrito de Chamartín',
                                        'Distrito de Moratalaz',
                                          'Distrito de Barajas',
                                  'Distrito de Moncloa-Aravaca',
                                        'Distrito de Vicálvaro',
                                       'Distrito de Villaverde',
                               'Distrito de Puente de Vallecas',
                              'Distrito de Fuencarral-El Pardo',
                            'Distrito de San Blas - Canillejas',
                                'Distrito de Villa de Vallecas',
                                         'Distrito de Chamberi',
           'Distrito de Tetuan                                ',
                           'Distrito de Puente de Vallecas    ',
                                          'Distrito de Centro ',
                                 'Distrito de Ciudad Lineal   ',
                                'Distrito de Ciudad Lineal    ',
                                   'Distrito de Villaverde    ',
                              'Distrito de Ciudad Lineal      ',
                             'Distrito de Puente de Vallecas  ',
                                        'Distrito de Chamartin',
           'Distrito de Usera                                 ',
           'Distrito de Ciudad Lineal                         ',
           'Distrito de Puente de Vallecas                    ',
           'Distrito de Carabanchel                           ',
           'Distrito de Villaverde                            ',
           'Distrito de Centro                                ',
           'Distrito de Barajas                               ',
           'Distrito de Fuencarral-El Pardo                   ',
           'Distrito de Retiro                                ',
           'Distrito de Latina                                ',
           'Distrito de Villa de Vallecas                     ',
                                  'Distrito de Chamberí       ',
           'Distrito de Salamanca                             ',
               'Distrito de Moratalaz                         ',
           'Distrito de Moratalaz                             ',
          'Distrito de Ciudad Lineal                          ',
                                          'Distrito de Latina ',
                            'Distrito de Ciudad Lineal        ',
                                    'Distrito de Hortaleza    ',
                           'Distrito de Fuencarral-El Pardo   ',
                              'Distrito de Villa de Vallecas  ',
                           'Distrito de San Blas - Canillejas ',
                                  'Distrito de Ciudad Lineal  ',
                                   'Distrito de Carabanchel   ',
                                   'Distrito de Ciudad Lineal ',
           'Distrito de Chamartín                             ',
          'Distrito de Salamanca                              ',
           'Distrito de San Blas - Canillejas                 ',
 'Distrito de Puente de Vallecas                              ',
              'Distrito de Usera                              ',
       'Distrito de Fuencarral - El Pardo                     ',
                              'Distrito de San Blas-Canillejas']
Length: 63, dtype: str

In [8]:
print(df['neighbourhood_group'].unique())

<StringArray>
[            'Chamartín',                'Latina',            'Arganzuela',
                'Centro',             'Salamanca', 'Fuencarral - El Pardo',
    'Puente de Vallecas',         'Ciudad Lineal',              'Chamberí',
            'Villaverde',             'Hortaleza',     'Moncloa - Aravaca',
           'Carabanchel',                'Tetuán',                'Retiro',
 'San Blas - Canillejas',     'Villa de Vallecas',               'Barajas',
                 'Usera',             'Moratalaz',             'Vicálvaro']
Length: 21, dtype: str

In [9]:
import re

# Lista de referencia: los 21 distritos tal y como están en el dataset de Airbnb (no se toca)
distritos_referencia = sorted(df['neighbourhood_group'].unique())

def normalizar_distrito(nombre):
    nombre = str(nombre).strip()
    nombre = nombre.replace('Distrito de ', '')
    nombre = re.sub(r'\s+', ' ', nombre)          # colapsa espacios múltiples
    nombre = re.sub(r'\s*-\s*', ' - ', nombre)     # guion siempre con espacios: " - "
    nombre = nombre.replace('Tetuan', 'Tetuán')    # corrige tilde que falta en el VUT
    return nombre.strip()

# Aplicar a las 4 fuentes propias
poblacion['distrito'] = poblacion['distrito'].apply(normalizar_distrito)
renta['distrito'] = renta['distrito'].apply(normalizar_distrito)
alquiler['distrito'] = alquiler['distrito'].apply(normalizar_distrito)
eventos['distrito'] = eventos['distrito'].apply(normalizar_distrito)

# Aplicar al VUT
vut['distrito'] = vut['DISTRITO'].apply(normalizar_distrito)

# Comprobar que todo cuadra con los 21 distritos de referencia
print("Referencia (21):", len(distritos_referencia))
print("Población OK:", set(poblacion['distrito']) == set(distritos_referencia))
print("Renta OK:", set(renta['distrito']) == set(distritos_referencia))
print("Alquiler OK:", set(alquiler['distrito']) == set(distritos_referencia))
print("Eventos OK:", set(eventos['distrito']) == set(distritos_referencia))
print("VUT distritos únicos tras normalizar:", sorted(vut['distrito'].unique()))
print("VUT OK:", set(vut['distrito']) == set(distritos_referencia))

Referencia (21): 21
Población OK: True
Renta OK: True
Alquiler OK: True
Eventos OK: True
VUT distritos únicos tras normalizar: ['Arganzuela', 'Barajas', 'Carabanchel', 'Centro', 'Chamartin', 'Chamartín', 'Chamberi', 'Chamberí', 'Ciudad Lineal', 'Fuencarral - El Pardo', 'Hortaleza', 'Latina', 'Moncloa - Aravaca', 'Moratalaz', 'Puente de Vallecas', 'Retiro', 'Salamanca', 'San Blas - Canillejas', 'Tetuán', 'Usera', 'Vicálvaro', 'Villa de Vallecas', 'Villaverde']
VUT OK: False

In [10]:
def normalizar_distrito(nombre):
    nombre = str(nombre).strip()
    nombre = nombre.replace('Distrito de ', '')
    nombre = re.sub(r'\s+', ' ', nombre)
    nombre = re.sub(r'\s*-\s*', ' - ', nombre)
    # Correcciones de tildes que faltan en el VUT
    nombre = nombre.replace('Tetuan', 'Tetuán')
    nombre = nombre.replace('Chamartin', 'Chamartín')
    nombre = nombre.replace('Chamberi', 'Chamberí')
    return nombre.strip()

# Volver a aplicar solo al VUT (las otras 4 ya salieron OK)
vut['distrito'] = vut['DISTRITO'].apply(normalizar_distrito)

print("VUT distritos únicos tras normalizar:", sorted(vut['distrito'].unique()))
print("VUT OK:", set(vut['distrito']) == set(distritos_referencia))

VUT distritos únicos tras normalizar: ['Arganzuela', 'Barajas', 'Carabanchel', 'Centro', 'Chamartín', 'Chamberí', 'Ciudad Lineal', 'Fuencarral - El Pardo', 'Hortaleza', 'Latina', 'Moncloa - Aravaca', 'Moratalaz', 'Puente de Vallecas', 'Retiro', 'Salamanca', 'San Blas - Canillejas', 'Tetuán', 'Usera', 'Vicálvaro', 'Villa de Vallecas', 'Villaverde']
VUT OK: True

In [11]:
vut_por_distrito = vut.groupby('distrito')['UNIDADES_VUT'].sum().reset_index()
vut_por_distrito.columns = ['distrito', 'total_vut']
print(vut_por_distrito.shape)
vut_por_distrito

(21, 2)

                 distrito  total_vut
0              Arganzuela        121
1                 Barajas         17
2             Carabanchel         85
3                  Centro        218
4               Chamartín        109
5                Chamberí         60
6           Ciudad Lineal        133
7   Fuencarral - El Pardo         52
8               Hortaleza         28
9                  Latina         68
10      Moncloa - Aravaca         24
11              Moratalaz         16
12     Puente de Vallecas         79
13                 Retiro         40
14              Salamanca         79
15  San Blas - Canillejas         18
16                 Tetuán        177
17                  Usera         48
18              Vicálvaro          7
19      Villa de Vallecas          9
20             Villaverde         17

In [12]:
df_enriched = df.merge(poblacion, left_on='neighbourhood_group', right_on='distrito', how='left') \
                .merge(renta, on='distrito', how='left') \
                .merge(alquiler, on='distrito', how='left') \
                .merge(eventos, on='distrito', how='left') \
                .merge(vut_por_distrito, on='distrito', how='left')

# Eliminar columnas 'distrito' duplicadas si sobran (nos quedamos con neighbourhood_group como clave original)
df_enriched = df_enriched.drop(columns=['distrito'])

print(df_enriched.shape)
df_enriched.head()

(19618, 21)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,...,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,poblacion_total,renta_media_hogar,alquiler_medio_mes,tiene_gran_recinto,total_vut
0,6369,"Rooftop terrace room , ensuite bathroom",13660,Simon,Chamartín,Hispanoamérica,40.45724,-3.67688,Private room,60.0,...,78,2020-09-20,0.58,1,180,148093,79274,951.72,1,109
1,21853,Bright and airy room,83531,Abdel,Latina,Cármenes,40.40381,-3.74130,Private room,31.0,...,33,2018-07-15,0.42,2,364,251139,38078,651.95,0,68
2,23001,Apartmento Arganzuela- Madrid Rio,82175,Jesus,Arganzuela,Legazpi,40.38840,-3.69511,Entire home/apt,50.0,...,0,NaN,0.00,7,1,158550,52857,850.00,0,121
3,24805,Gran Via Studio Madrid,346366726,A,Centro,Universidad,40.42183,-3.70529,Entire home/apt,92.0,...,10,2020-03-01,0.13,1,72,141800,44958,825.00,1,218
4,26825,Single Room whith private Bathroom,114340,Agustina,Arganzuela,Legazpi,40.38975,-3.69018,Private room,26.0,...,149,2020-03-12,1.12,1,365,158550,52857,850.00,0,121

In [14]:
# Comprobar que no falte ningún dato tras el merge
columnas_nuevas = ['poblacion_total', 'renta_media', 'precio_alquiler', 'evento', 'total_vut']
print(df_enriched[columnas_nuevas].isnull().sum())

KeyError: "['renta_media', 'precio_alquiler', 'evento'] not in index"

In [15]:
print(df_enriched.columns.tolist())

['id', 'name', 'host_id', 'host_name', 'neighbourhood_group', 'neighbourhood', 'latitude', 'longitude', 'room_type', 'price', 'minimum_nights', 'number_of_reviews', 'last_review', 'reviews_per_month', 'calculated_host_listings_count', 'availability_365', 'poblacion_total', 'renta_media_hogar', 'alquiler_medio_mes', 'tiene_gran_recinto', 'total_vut']

In [16]:
columnas_nuevas = ['poblacion_total', 'renta_media_hogar', 'alquiler_medio_mes', 'tiene_gran_recinto', 'total_vut']
print(df_enriched[columnas_nuevas].isnull().sum())

poblacion_total       0
renta_media_hogar     0
alquiler_medio_mes    0
tiene_gran_recinto    0
total_vut             0
dtype: int64

In [18]:
df_enriched.to_csv('../data/processed/madrid_airbnb_enriched.csv', index=False)

## Resumen del enriquecimiento de datos

Este notebook enriquece el dataset limpio de Airbnb Madrid con cinco variables a nivel de distrito, obtenidas del Ayuntamiento de Madrid / INE, usando `neighbourhood_group` como clave de unión.

**Fuentes de enriquecimiento:**

| Variable | Descripción | Fuente |
|---|---|---|
| `poblacion_total` | Población total por distrito (Padrón Municipal) | Ayuntamiento de Madrid |
| `renta_media_hogar` | Renta media por hogar y distrito | Ayuntamiento de Madrid / INE Atlas de renta |
| `alquiler_medio_mes` | Precio de alquiler de referencia por distrito | Ayuntamiento de Madrid |
| `tiene_gran_recinto` | Indicador binario: si el distrito tiene un gran recinto de eventos | Elaboración propia (pandas) |
| `total_vut` | Total de viviendas de uso turístico (VUT) con licencia por distrito | Geoportal Ayuntamiento de Madrid |

**Pasos principales:**
1. Carga del dataset limpio de Airbnb (`madrid_airbnb_clean.csv`) y de las cinco fuentes de enriquecimiento.
2. Normalización de los nombres de distrito entre fuentes — el dataset VUT requería eliminar el prefijo `"Distrito de "`, quitar espacios sobrantes, unificar el formato del guion y corregir tildes faltantes (Tetuán, Chamartín, Chamberí).
3. Agregación del VUT por distrito, sumando `UNIDADES_VUT` en `total_vut`.
4. Merge tipo `left` de las cinco fuentes sobre el dataset original usando `neighbourhood_group` como clave, conservando las 19.618 filas originales.
5. Verificación de que no se introdujeron valores nulos en ninguna de las cinco columnas nuevas.

**Resultado:** `df_enriched` — 19.618 filas × 21 columnas, guardado en `../data/processed/madrid_airbnb_enriched.csv`. Las columnas originales de Airbnb no fueron modificadas, conforme a los requisitos del proyecto.